{
  flake.homeModules.ghostty =
    {
      config,
      pkgs,
      ...
    }:
    {
      rum.programs.ghostty = {
        enable = true;

        settings = {
          font-family = config.theme.font.mono.name;
          font-size = config.theme.font.size.normal;

          gtk-titlebar = false;

          window-padding-x = config.theme.padding;
          window-padding-y = config.theme.padding;

          # Colours come from the base16 theme, generated by ThemeNix.
          config-file = "${pkgs.writeText "ghostty-theme" config.theme.ghosttyConfig}";

          # 100 MiB
          scrollback-limit = 100 * 1024 * 1024;

          mouse-hide-while-typing = true;
          quit-after-last-window-closed = true;
        };
      };
    };
}
